services:
  db:
    image: postgres:15-alpine
    container_name: jimbos-show-log-postgresdb
    restart: always
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jimbos-network

  backend:
    build: ./backend
    container_name: jimbos_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env.docker
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PORT: 3000
      NODE_ENV: production
    volumes:
      - uploads_data:/app/uploads
    networks:
      - jimbos-network

  frontend:
    build: ./frontend
    container_name: jimbos_frontend
    restart: always
    ports:
      - "1995:80"
    depends_on:
      - backend
    volumes:
      - uploads_data:/usr/share/nginx/html/uploads
    networks:
      - jimbos-network

volumes:
  postgres_data:
  uploads_data:

networks:
  jimbos-network:
    driver: bridge